### ISSUE TITLE
ERROR: scipy-1.6.0-cp38-cp38-macosx_11_1_arm64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by simion** [rybodiddly/Poetry-Pyenv-Homebrew-Numpy-TensorFlow-on-Apple-Silicon-M1#1]
Hi,

Almost everything worked so far, except scipy and Pillow (from your repo).

`pip install  tensorflow-2.4.0rc0-cp38-cp38-macosx_11_0_arm64.whl` - works fine

`pip install scipy-1.6.0-cp38-cp38-macosx_11_1_arm64.whl` 
 **ERROR: scipy-1.6.0-cp38-cp38-macosx_11_1_arm64.whl is not a supported wheel on this platform.**

`pip install Pillow-8.1.0-cp38-cp38-macosx_11_1_arm64.whl` 
**ERROR: Pillow-8.1.0-cp38-cp38-macosx_11_1_arm64.whl is not a supported wheel on this platform.**

I have macOS bigSur 11.1 (20C69) on the new Macbook Air.

Any ideas? :D i don't use scipy directly, it's a dependency for another package. I just want to get it installed, doesn't matter if it does not work properly.

Thanks and great work with the guide!

**Comment by rybodiddly** [comment]
What version of python are you running? `python -V`. That error message usual relates to the python version. The `cp38` is from it being built on python 3.8.6. Also, make sure pip isn't calling python 2's pip. I just downloaded the source and built the wheels `python setup.py bdist_wheel`. Just make sure each has the required dependencies when building. They were also built to be used in a poetry environment with the manual installation methods outlined in the guide. Haven't tried through pip yet.

You might want to look into [miniforge3](https://github.com/conda-forge/miniforge). You can use the Apple tensorflow repack and addons, but miniforge has all the other modules ready for installation and working out of the box. Probably the most stable ML/AI dev environment at the moment for Apple Silicon.

**Comment by simion** [comment]
It’s python 3.8.6, the exact version from your tutorial.

**Comment by rybodiddly** [comment]
Looked into this a little further, but need to know a little more about your pip usage. if you type `which pip`, what's the output location? The way pip should be used in conjunction with poetry is to type `poetry run pip install scipy-1.6.0-cp38-cp38-macosx_11_1_arm64.whl` from within your poetry environment/project folder. The guide had suggested to use `poetry add scipy`, which would check the project.toml file and find the wheel location. The guide also has it setup so you can't call pip without an activated virtual environment (you had to use gpip), which was designed to prevent against accidental installation into your global environment. I just tested the scipy and pillow wheels, and both installed correctly into a new poetry folder using the `poetry run pip install scipy-1.6.0-cp38-cp38-macosx_11_1_arm64.whl` method. But i also noticed that pillow no longer requires the wheel, meaning the repository has been fixed for arm64 and can just be installed normally via pip.

**Comment by simion** [comment]
I'm running everything under the poetry virtualenv by using `poetry shell`. 

```
❯ which pip                                                                                                                
/Users/simion/Library/Caches/pypoetry/virtualenvs/clandesto-u46arpdC-py3.8/bin/pip
❯ which python                                                                                                              
/Users/simion/Library/Caches/pypoetry/virtualenvs/clandesto-u46arpdC-py3.8/bin/python
❯ python -V
Python 3.8.7
❯ pip install scipy-1.6.0-cp38-cp38-macosx_11_1_arm64.whl
ERROR: scipy-1.6.0-cp38-cp38-macosx_11_1_arm64.whl is not a supported wheel on this platform.
```

**Comment by simion** [comment]
My bad, seems to work under `3.8.6` but not under `3.8.7`. :D 
Thanks and great work! <3

**Comment by rybodiddly** [comment]
Glad you got it figured out. But, yes the wheels were built using 3.8.6. Will make sure to note the version requirement in the guide. Thanks for the discovery. Will mark this as closed.
